version: 2
jobs:
  gofmt:
    docker:
      - image: circleci/golang:1.9
    working_directory: /go/src/github.com/antifuchs/o
    steps:
      - checkout
      - run:
          name: gofmt
          command: |
            gofmt -w .
      - run:
          name: Check for differences
          command: |
            git add . && git diff --cached && git diff-index --cached --exit-code HEAD

  tests:
    docker:
      - image: circleci/golang:1.9
    working_directory: /go/src/github.com/antifuchs/o
    steps:
      - checkout
      - run:
          name: deps
          command: |
            go get -v -t -d ./...
      - run:
          name: "Create a temp directory for artifacts"
          command: |
            mkdir -p /tmp/artifacts
      - run:
          name: Run tests
          # This trick comes from https://medium.com/@taowen/go-test-coverage-for-multi-package-project-d4f36f2b573a:
          command: |
            srcpkg="$(go list ./... | grep -v vendor | tr "\n" , | sed 's/,$//')"
            for d in $(go list ./... | grep -v vendor); do
                go test -race -coverprofile=profile.out -timeout=60s -coverpkg="$srcpkg" -v $d
                if [ -f profile.out ]; then
                    cat profile.out >> coverage.txt
                    rm profile.out
                fi
            done
            go tool cover -html=coverage.txt -o /tmp/artifacts/coverage.html
      - store_artifacts:
          path: /tmp/artifacts

  benchmarks:
    docker:
      - image: circleci/golang:1.9
    working_directory: /go/src/github.com/antifuchs/o
    steps:
      - checkout
      - run:
          name: gofmt
          command: |
            gofmt -w .
      - run:
          name: deps
          command: |
            go get -v -t -d ./...
      - run:
          name: Run benchmarks
          command: |
            go test -run '^$' -bench . -v ./...

  ci_success:
    docker:
      - image: alpine:latest
    steps:
      - run:
          name: Success
          command: "echo yay"

workflows:
  version: 2
  continuous_integration:
    jobs:
      - gofmt
      - tests
      - benchmarks
      - ci_success:
          requires:
            - gofmt
            - tests
            - benchmarks
